env:
  mocha: true
  browser: true
  node: true
  jquery: true
  es6: true
extends: standard
plugins:
  - standard
  - promise
rules:
  arrow-parens: 0
  eqeqeq: 0
  no-return-assign: 0 # fails for arrow functions
  semi: [1, always]
  space-before-function-paren: [1, never]
  yoda: 0
  arrow-spacing: 2
  dot-location: [1, "property"]
  space-infix-ops: 0
  eol-last: [0, "never"]
  indent: [1, 4]
  no-unused-vars: 1